#!/usr/bin/env python3
"""Seed sample medical documents for testing the appeal workflow."""

import os
import shutil
from pymongo import MongoClient
from datetime import datetime
from pathlib import Path

# MongoDB connection
client = MongoClient('mongodb://localhost:27017/')
db = client['penguin_app']
denials_collection = db['denials']
documents_collection = db['documents']

# Path to test files
TEST_FILES_PATH = "/Users/vaatsav/Desktop/claude-code-agents/test_files"

# Document mappings for each denial
document_mappings = {
    "CLM-2025-001": [
        {
            "file_name": "medical_chart_notes.pdf",
            "document_type": "medical_records",
            "document_date": "2025-01-10",
            "description": "Medical chart notes documenting chronic back pain"
        },
        {
            "file_name": "imaging_report.pdf",
            "document_type": "imaging",
            "document_date": "2025-01-08",
            "description": "MRI showing lumbar spine issues"
        }
    ],
    "CLM-2025-002": [
        {
            "file_name": "operative_report.pdf",
            "document_type": "operative_report",
            "document_date": "2025-01-10",
            "description": "Operative report for knee arthroplasty"
        },
        {
            "file_name": "medical_chart_notes.pdf",
            "document_type": "medical_records",
            "document_date": "2025-01-05",
            "description": "Pre-operative evaluation notes"
        }
    ],
    "CLM-2025-003": [
        {
            "file_name": "imaging_report.pdf",
            "document_type": "imaging",
            "document_date": "2025-01-12",
            "description": "MRI lumbar spine report"
        },
        {
            "file_name": "physical_therapy_notes.pdf",
            "document_type": "therapy_notes",
            "document_date": "2024-12-15",
            "description": "6 weeks of physical therapy documentation"
        }
    ]
}

def seed_documents():
    """Seed sample documents for testing."""
    print("Starting document seeding...")

    if not os.path.exists(TEST_FILES_PATH):
        print(f"⚠️  Test files directory not found: {TEST_FILES_PATH}")
        print("   Documents will be created as placeholders only.")

    total_added = 0

    for claim_number, docs in document_mappings.items():
        # Find the denial
        denial = denials_collection.find_one({"claim_number": claim_number})
        if not denial:
            print(f"⚠️  Denial {claim_number} not found, skipping documents...")
            continue

        denial_id = str(denial['_id'])
        patient_id = denial['patient_id']

        print(f"\n📄 Adding documents for {claim_number} ({denial['patient_name']})...")

        for doc_info in docs:
            # Check if document already exists
            existing = documents_collection.find_one({
                "denial_id": denial_id,
                "document_type": doc_info["document_type"]
            })

            if existing:
                print(f"   ⚠️  Document already exists: {doc_info['document_type']}")
                continue

            # Create document record
            doc_record = {
                "denial_id": denial_id,
                "patient_id": patient_id,
                "claim_number": claim_number,
                "document_name": f"{claim_number}_{doc_info['document_type']}.pdf",
                "document_type": doc_info["document_type"],
                "document_date": datetime.fromisoformat(doc_info["document_date"]),
                "description": doc_info["description"],
                "file_path": f"/uploads/{denial_id}/{doc_info['document_type']}.pdf",
                "page_count": 3,  # Placeholder
                "presigned_urls": {},  # Will be generated by backend
                "status": "processed",
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow()
            }

            # Insert document
            result = documents_collection.insert_one(doc_record)
            total_added += 1
            print(f"   ✓ Added: {doc_info['document_type']} - {doc_info['description']}")

    print(f"\n✅ Document seeding complete! Added {total_added} documents.")
    print(f"   Total documents in database: {documents_collection.count_documents({})}")
    print("\n💡 Note: Document files are placeholders. To test with real PDFs:")
    print(f"   1. Upload PDFs through the UI")
    print(f"   2. Or copy test PDFs to: {TEST_FILES_PATH}")

if __name__ == "__main__":
    try:
        seed_documents()
    except Exception as e:
        print(f"❌ Error seeding documents: {str(e)}")
        import traceback
        traceback.print_exc()
